### ISSUE TITLE
include a schema definition for KEV data

### ISSUE THREAD

**Issue by jwoytek-cisa** [cisagov/vulnrichment#17]
# 💡 Summary #

Include a JSON schema definition for KEV data in `metrics`. The data also exists in `timeline`, but that data is formatted for and can be validated against the CVE JSON schema for `timeline` entries. 

## Motivation and context ##

`metrics` objects of type `other` have a flexible definition to allow different types of metrics to be conveyed in the data. The SSVC metrics data conforms to the SSVC JSON schema. However, the schema for KEV data entries in `metrics` is not defined. While the `metrics` data will validate against the CVE JSON schema, there is currently nothing against which the KEV data can be validated.

**Comment by amanion-cisa** [comment]
Proposed addition to README.md.

### Schemas and validation

CWE, CVSS, and CPE enrichment data conforms to the CVE Record Format [schema](https://github.com/CVEProject/cve-schema/).

SSVC is implemented as a `metrics` type of `other` and conforms to the SSVC [schema](https://github.com/CERTCC/SSVC/tree/main/data/schema). SSVC keys and values are case insensitive and may in the future be normalized to lower case (see #16).

KEV is implemented as a `metrics` type of `other` and also with `timeline`. A KEV schema is forthcoming.

**Comment by sei-vsarvepalli** [comment]
The addition to README.md will be good. However one useful way is to provide a ADP expected schema that brings all these elements together, with its own version numbering. The purpose is to let people know how to scan the ADP record. It will help as ADP record evolves and adds other fields or newer versions of the fields to the record.  For e.g., If a new CVE version has a different "affected" field you can upgrade and let your audience know which version of the CVE.affected field you are supporting.  

This ADP expected schema can be in the Vulnrichment repo and optionally left a bit open ended, schema field of "additionalProperties" can be even set to "true" allowing things to evolve as well. The idea is to give people some orientation as to what is available in the ADP record and how to parse the information. Hope that helps.

https://json-schema.org/understanding-json-schema/structuring#json-pointer
