### ISSUE TITLE
Clarify a sentence in the README

### ISSUE THREAD

**Issue by joshbressers** [cisagov/vulnrichment#6]
This sentence in the README is confusing

_Producers and consumers of this CVE data should already be familiar with the current [JSON format](https://www.cve.org/Media/News/item/blog/2023/03/29/CVE-Downloads-in-JSON-5-Format), and can access this data in the normal ways, including the [GitHub API](https://docs.github.com/en/rest/quickstart)._

Is the intent of the GitHub API link to suggest using Git to download the data, or is there some other API access you have in mind?

**Comment by todb-cisa** [comment]
Just a suggestion -- basically, "however you normally take and process data sets from a GitHub repo, just do that."

This is a temporary consumer situation, though, as the README goes on to say, "[t]his project is expected to evolve quickly over the next several weeks." My hope is that the ADP gears start turning soon-ish, and all this ADP will get reabsorbed back up into the main CVE corpus. But, the important part is just getting the data out there, and giving people a chance to mess around with it, find bugs, do the normal open-source thing.

**Comment by todb-cisa** [comment]
I don't think there's anything to do here right now -- once ADP is fired up and going, we can update the README to talk more about ADP, but that's still a little ways off. Re-open if you have a better suggestion!
