### ISSUE TITLE
Readme has incorrect line numbers and links to code

### ISSUE THREAD

**Issue by nicpenning** [cisagov/vulnrichment#99]
# 🐛 Summary #

All line numbers and references are incorrect for the examples.

## To reproduce ##

1. Check out the read me and click on the line references. 

## Expected behavior ##

I expect the code align to what is shown/expected.

**Comment by amanion-cisa** [comment]
Will probably need to use quoted/self-contained examples, line numbers could continue to drift as container data changes.

**Comment by todb-cisa** [comment]
Indeed they do. That said, examples should be mostly fixed and static now. I'll bop through and find the right line numbers and such. Thanks for the eyeballing!
